AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Identity Center with permission sets

Parameters:
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development
  # https://dev.to/hayao_k/how-to-manage-aws-sso-account-assignments-in-cloudformaton-5bmm
  identityCenterInstanceArn:
    Type: String
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html#cfn-sso-permissionset-instancearn
    AllowedPattern: arn:aws:sso:::instance/(sso)?ins-[a-zA-Z0-9-.]{16}
    Description: ARN of an IAM Identity Center, e.g. 'arn:aws:sso:::instance/ssoins-xxxxxxxxxxxxxxxx'
  organizationRootId:
    Type: String
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-organizationalunit.html#cfn-organizations-organizationalunit-parentid
    AllowedPattern: ^(r-[0-9a-z]{4,32})|(ou-[0-9a-z]{4,32}-[a-z0-9]{8,32})$
    Description: Root ID of the organization
  securityAccountId:
    Type: String
    Description: ID of the security account
  supportedRegions:
    Type: String
    Description: Comma separated list of supported regions
  organizationsAwsServiceAccessFunctionArn:
    Type: String
    Description: AWS Service Access custom resource Lambda function ARN
  cloudformationOrganizationsAccessFunctionArn:
    Type: String
    Description: Cloudformation organizations access custom resource Lambda function ARN
  organizationsDelegatedAdministratorFunctionArn:
    Type: String
    Description: Cloudformation organizations delegated administrator custom resource Lambda function ARN
  policyNamePostfix:
    Type: String
    Description: Postfix to make policy names unique
    Default: G6U4SR
  policyPath:
    Type: String
    Description: Organization policy path
    Default: "/org/"

Resources:
  EnableSsoOrganizationsAccess:
    Type: Custom::OrganizationsServiceAccess
    Properties:
      ServiceToken: !Ref organizationsAwsServiceAccessFunctionArn
      ServiceTimeout: 30
      service: sso.amazonaws.com

  IdentityCenterDelegatedAdministrator:
    Type: Custom::OrganizationsDelegatedAdministrator
    DependsOn: EnableSsoOrganizationsAccess
    Properties:
      ServiceToken: !Ref organizationsDelegatedAdministratorFunctionArn
      ServiceTimeout: 10
      accountId: !Ref securityAccountId
      service: sso.amazonaws.com

  # Enabling trusted access for StackSets ONLY works through Cloudformation API
  # CloudFormation does not support service-linked roles
  # See:
  #   https://docs.aws.amazon.com/organizations/latest/userguide/services-that-can-integrate-cloudformation.html
  #   https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html
  EnableCloudFormationOrganizationsAccess:
    Type: Custom::CloudFormationOrganizationsAccess
    DependsOn:
      - EnableSsoOrganizationsAccess
    Properties:
      ServiceToken: !Ref cloudformationOrganizationsAccessFunctionArn
      ServiceTimeout: 30

  # Policies
  OrganizationPoliciesStack:
    # Organization policies for management account.
    # When using SERVICE_MANAGED StackSets, StackSets are not deployed automatically to the management account.
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        environment: !Ref environment
        policyNamePostfix: !Ref policyNamePostfix
        policyPath: !Ref policyPath
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: ./managed-policies.yml
      TimeoutInMinutes: 10

  OrganizationPoliciesStackSet:
    Type: AWS::CloudFormation::StackSet
    DependsOn:
      - EnableCloudFormationOrganizationsAccess
    Properties:
      StackSetName: !Sub "OrganizationPolicies-${environment}"
      Description: Managed organization policies for each account
      TemplateURL: ./managed-policies.yml
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      CallAs: SELF
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Parameters:
        - ParameterKey: environment
          ParameterValue: !Ref environment
        - ParameterKey: policyNamePostfix
          ParameterValue: !Ref policyNamePostfix
        - ParameterKey: policyPath
          ParameterValue: !Ref policyPath
      PermissionModel: SERVICE_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref organizationRootId
          Regions:
            # Deploy to main region only
            - !Ref AWS::Region
      Tags:
        - Key: environment
          Value: !Ref environment

  ##
  # Management account permission sets
  ##
  ManagementAdministratorPermissionSet:
    Type: AWS::SSO::PermissionSet
    DependsOn:
      - OrganizationPoliciesStackSet
      - OrganizationPoliciesStack
    Properties:
      Name: ManagementAdministrator
      Description: Administrator for management account, allowed to do everything
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: module
          Value: management

  ManagementPowerUserPermissionSet:
    Type: AWS::SSO::PermissionSet
    DependsOn:
      - OrganizationPoliciesStackSet
      - OrganizationPoliciesStack
    Properties:
      Name: ManagementPowerUser
      Description: Power user for management account, based on AWS PowerUser policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/PowerUserAccess"
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: module
          Value: management

  ManagementReadOnlyPermissionSet:
    Type: AWS::SSO::PermissionSet
    DependsOn:
      - OrganizationPoliciesStackSet
      - OrganizationPoliciesStack
    Properties:
      Name: ManagementReadOnly
      Description: Read only access for management account, based on AWS ReadOnlyAccess policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/ReadOnlyAccess"
      Tags:
        - Key: environment
          Value: !Ref environment
        - Key: module
          Value: management

  ##
  # Permission sets for normal accounts
  ##
  AdministratorPermissionSet:
    Type: AWS::SSO::PermissionSet
    DependsOn:
      - OrganizationPoliciesStackSet
      - OrganizationPoliciesStack
    Properties:
      Name: Administrator
      Description: Administrator, allowed to do everything
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess"
      Tags:
        - Key: environment
          Value: !Ref environment

  PowerUserPermissionSet:
    Type: AWS::SSO::PermissionSet
    DependsOn:
      - OrganizationPoliciesStackSet
      - OrganizationPoliciesStack
    Properties:
      Name: PowerUser
      Description: Power user based on AWS PowerUser policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/PowerUserAccess"
      CustomerManagedPolicyReferences:
        - Name: !GetAtt OrganizationPoliciesStack.Outputs.DenyIamUserCreationName
          Path: !Ref policyPath
      InlinePolicy:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            Location: ./poweruser-policy-v1.json
      Tags:
        - Key: environment
          Value: !Ref environment

  ReadOnlyPermissionSet:
    Type: AWS::SSO::PermissionSet
    DependsOn:
      - OrganizationPoliciesStackSet
      - OrganizationPoliciesStack
    Properties:
      Name: ReadOnly
      Description: Read only access based on AWS ReadOnlyAccess policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/ReadOnlyAccess"
      Tags:
        - Key: environment
          Value: !Ref environment

  UserManagerPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: UserManager
      Description: Manage Identity Store / SSO users
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSSSOReadOnly"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSSSODirectoryReadOnly"
      InlinePolicy:
        "Fn::Transform":
          Name: "AWS::Include"
          Parameters:
            # Update version number when changing the policy
            # Otherwise CloudFormation will not register the change
            Location: ./user-manager-policy-v3.json
            # TODO limit permission to organization and account
      Tags:
        - Key: environment
          Value: !Ref environment

Outputs:
  PermissionSets:
    Description: Identity center permission sets
    Value: !Sub
      - |
        Administrator: "${AdministratorPermissionSetArn}"
        PowerUser: "${PowerUserPermissionSetArn}"
        ReadOnly: "${ReadOnlyPermissionSetArn}"
        UserManager: "${UserManagerPermissionSetArn}"
      - AdministratorPermissionSetArn: !GetAtt AdministratorPermissionSet.PermissionSetArn
        PowerUserPermissionSetArn: !GetAtt PowerUserPermissionSet.PermissionSetArn
        ReadOnlyPermissionSetArn: !GetAtt ReadOnlyPermissionSet.PermissionSetArn
        UserManagerPermissionSetArn: !GetAtt UserManagerPermissionSet.PermissionSetArn
