AWSTemplateFormatVersion: 2010-09-09

# WARNING
# Stack sets with service-managed permissions don't currently support the use of macros in templates. (This includes the AWS::Include and AWS::Serverless transforms, which are macros hosted by CloudFormation.)
# See https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack-set.html

Description: Organization policies

Parameters:
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development
  policyPath:
    Type: String
    Description: Organization policy path
  policyNamePostfix:
    Type: String
    Description: Postfix to make policy names unique

Resources:
  ManageOwnMfaDevicePolicy:
    # This policy is for IAM users only. Do not use it for Identity Center users,
    # because "aws:MultiFactorAuthPresent" is not true for these users
    # and it would block all access for them
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "ManageOwnMfaDevice-${AWS::Region}-${environment}-${policyNamePostfix}"
      Description: Manage own FMA device
      Path: !Ref policyPath
      PolicyDocument:
        # See https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage-mfa-only.html
        Version: 2012-10-17
        Statement:
          - Sid: AllowViewAccountInfo
            Effect: Allow
            Action: iam:ListVirtualMFADevices
            Resource: "*"
          - Sid: AllowManageOwnVirtualMFADevice
            Effect: Allow
            Action:
              - iam:CreateVirtualMFADevice
            Resource: arn:aws:iam::*:mfa/*
          - Sid: AllowManageOwnUserMFA
            Effect: Allow
            Action:
              - iam:DeactivateMFADevice
              - iam:EnableMFADevice
              - iam:GetUser
              - iam:GetMFADevice
              - iam:ListMFADevices
              - iam:ResyncMFADevice
            Resource: arn:aws:iam::*:user/${aws:username}
          - Sid: DenyAllExceptListedIfNoMFA
            Effect: Deny
            NotAction:
              - iam:CreateVirtualMFADevice
              - iam:EnableMFADevice
              - iam:GetUser
              - iam:ListMFADevices
              - iam:ListVirtualMFADevices
              - iam:ResyncMFADevice
              - sts:GetSessionToken
            Resource: "*"
            Condition:
              BoolIfExists:
                "aws:MultiFactorAuthPresent": false

  DenyIamUserCreationPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "DenyIamUserCreation-${AWS::Region}-${environment}-${policyNamePostfix}"
      Description: Do not allow to create IAM users or access keys
      Path: !Ref policyPath
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyIamUserCreation
            Effect: Deny
            Action:
              - iam:CreateUser
              - iam:CreateAccessKey
            Resource: "*"

Outputs:
  ManageOwnMfaDevicePolicyName:
    Description: ManageOwnMfaDevicePolicy name
    Value: !Select [2, !Split ["/", !Ref ManageOwnMfaDevicePolicy]]
  DenyIamUserCreationName:
    Description: DenyIamUserCreationPolicy name
    Value: !Select [2, !Split ["/", !Ref DenyIamUserCreationPolicy]]
