AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Custom resources for AWS Organizations

Parameters:
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development
  organizationId:
    Type: String
    Description: Organization ID
  architecture:
    Type: String
    Default: arm64
    AllowedValues:
      - arm64
      - x86_64
    Description: Compute architecture, e.g. arm64
  powertoolsNameVersion:
    Type: String
    Default: AWSLambdaPowertoolsPythonV2-Arm64:73
    Description: Powertools name and version, e.g. AWSLambdaPowertoolsPythonV2-Arm64:71
  pythonVersion:
    Type: String
    Default: python3.9
    Description: Python version, e.g. python3.9

Conditions:
  IsEnvProd: !Equals
    - !Ref environment
    - futureprod # TODO "prod"

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: !Ref pythonVersion
    Architectures:
      - !Ref architecture
    Environment:
      Variables:
        LOG_LEVEL: !If [IsEnvProd, "WARNING", "INFO"]
        POWERTOOLS_LOGGER_LOG_EVENT: !If [IsEnvProd, false, true]
        POWERTOOLS_METRICS_NAMESPACE: cloudformation-custom-resources
        POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
    Tags:
      application: cloudformation-custom-resources
      environment: !Ref environment

Resources:
  # https://www.alexdebrie.com/posts/cloudformation-custom-resources/
  CustomResourceHelperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      # https://docs.aws.amazon.com/lambda/latest/dg/layers-sam.html
      LayerName: !Sub "custom-resource-helper-${environment}"
      Description: Custom Resource Helper for Python https://github.com/aws-cloudformation/custom-resource-helper
      ContentUri: "./lambda/custom_resource_helper/dependencies"
      CompatibleRuntimes:
        - !Ref pythonVersion
      CompatibleArchitectures:
        - !Ref architecture
    Metadata:
      BuildMethod: !Ref pythonVersion

  ##
  # CloudformationOrganizationsAccess
  ##
  CloudformationOrganizationsAccessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "cloudformation-organizations-access-dependencies-${environment}"
      Description: CloudformationOrganizationsAccessFunction dependencies
      ContentUri: "./lambda/cloudformation_organizations_access/dependencies"
      CompatibleRuntimes:
        - !Ref pythonVersion
      CompatibleArchitectures:
        - !Ref architecture
    Metadata:
      BuildMethod: !Ref pythonVersion

  CloudformationOrganizationsAccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "cloudformation-organizations-access-${environment}"
      Description: Enable/disable trusted access for cloudformation
      Handler: index.handler
      CodeUri: "./lambda/cloudformation_organizations_access/src"
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:017000801446:layer:${powertoolsNameVersion}"
        - !Ref CustomResourceHelperLayer
        - !Ref CloudformationOrganizationsAccessLayer
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: cloudformation_organizations_access
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_integrate_services.html
            - Sid: AllowEnableDisableOrganizationsAccess
              Effect: Allow
              Action:
                - organizations:ListAWSServiceAccessForOrganization
                - organizations:DescribeOrganization
                - organizations:EnableAWSServiceAccess
                - organizations:DisableAWSServiceAccess
              Resource: "*" # Only * supported
              Condition:
                StringEquals:
                  "aws:PrincipalOrgId":
                    - !Ref organizationId
            - Sid: AllowServiceLinkedRoleCreation
              Effect: Allow
              Action:
                - iam:GetRole
                - iam:CreateServiceLinkedRole
              Resource:
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/stacksets.cloudformation.amazonaws.com/"
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/stacksets.cloudformation.amazonaws.com/*"
            - Sid: AllowActivateDeactivateCloudFormationOrganizationsAccess
              Effect: Allow
              Action:
                - cloudformation:DescribeOrganizationsAccess
                - cloudformation:ActivateOrganizationsAccess
                - cloudformation:DeactivateOrganizationsAccess
              Resource: "*" # Only * supported

  # Force lambda logs to be retained only 1 week
  CloudformationOrganizationsAccessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [CloudformationOrganizationsAccessFunction]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CloudformationOrganizationsAccessFunction}"
      RetentionInDays: 7
      Tags:
        - Key: application
          Value: cloudformation-custom-resources
        - Key: environment
          Value: !Ref environment

  ##
  # OrganizationsAwsServiceAccess
  ##
  OrganizationsAwsServiceAccessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "organizations-aws-service-access-dependencies-${environment}"
      Description: OrganizationsAwsServiceAccessFunction dependencies
      ContentUri: "./lambda/organizations_aws_service_access/dependencies"
      CompatibleRuntimes:
        - !Ref pythonVersion
      CompatibleArchitectures:
        - !Ref architecture
    Metadata:
      BuildMethod: !Ref pythonVersion

  OrganizationsAwsServiceAccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "organizations-aws-service-access-${environment}"
      Description: Enable/disable trusted access for a service
      Handler: index.handler
      CodeUri: "./lambda/organizations_aws_service_access/src"
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:017000801446:layer:${powertoolsNameVersion}"
        - !Ref CustomResourceHelperLayer
        - !Ref OrganizationsAwsServiceAccessLayer
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: organizations_aws_service_access
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - organizations:ListAWSServiceAccessForOrganization
                - organizations:EnableAWSServiceAccess
                - organizations:DisableAWSServiceAccess
              Resource: "*" # Only * supported
              Condition:
                StringEquals:
                  "aws:PrincipalOrgId":
                    - !Ref organizationId
            - Effect: Allow
              Action:
                - iam:GetRole
                - iam:CreateServiceLinkedRole
              Resource:
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/*.amazonaws.com/"
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/*.amazonaws.com/*"

  # Force lambda logs to be retained only 1 week
  OrganizationsAwsServiceAccessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [OrganizationsAwsServiceAccessFunction]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${OrganizationsAwsServiceAccessFunction}"
      RetentionInDays: 7
      Tags:
        - Key: application
          Value: cloudformation-custom-resources
        - Key: environment
          Value: !Ref environment

  ##
  # OrganizationsPolicyType
  ##
  OrganizationsPolicyTypeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "organizations-policy-type-dependencies-${environment}"
      Description: OrganizationsPolicyTypeFunction dependencies
      ContentUri: "./lambda/organizations_policy_type/dependencies"
      CompatibleRuntimes:
        - !Ref pythonVersion
      CompatibleArchitectures:
        - !Ref architecture
    Metadata:
      BuildMethod: !Ref pythonVersion

  OrganizationsPolicyTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "organizations-policy-type-${environment}"
      Description: Enable/disable an organizations policy type
      Handler: index.handler
      CodeUri: "./lambda/organizations_policy_type/src"
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:017000801446:layer:${powertoolsNameVersion}"
        - !Ref CustomResourceHelperLayer
        - !Ref OrganizationsPolicyTypeLayer
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: organizations_policy_type
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Sid: AllowDescribeOrganization
              Effect: Allow
              Action:
                - organizations:ListRoots
                - organizations:DescribeOrganization
              Resource: "*" # Only * supported
              Condition:
                StringEquals:
                  "aws:PrincipalOrgId":
                    - !Ref organizationId
            - Sid: AllowEnableDisablePolicyType
              Effect: Allow
              Action:
                - organizations:EnablePolicyType
                - organizations:DisablePolicyType
              Resource:
                - !Sub "arn:aws:organizations::${AWS::AccountId}:root/o-*/r-*"

  # Force lambda logs to be retained only 1 week
  OrganizationsPolicyTypeFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [OrganizationsPolicyTypeFunction]
    Properties:
      LogGroupName: !Sub "/aws/lambda/${OrganizationsPolicyTypeFunction}"
      RetentionInDays: 7
      Tags:
        - Key: application
          Value: cloudformation-custom-resources
        - Key: environment
          Value: !Ref environment

Outputs:
  CloudformationOrganizationsAccessFunctionArn:
    Description: "ARN for the CloudformationOrganizationsAccessFunction custom resource function"
    Value: !GetAtt CloudformationOrganizationsAccessFunction.Arn
  OrganizationsAwsServiceAccessFunctionArn:
    Description: "ARN for the OrganizationsAwsServiceAccessFunction custom resource function"
    Value: !GetAtt OrganizationsAwsServiceAccessFunction.Arn
  OrganizationsPolicyTypeFunctionArn:
    Description: "ARN for the OrganizationsPolicyTypeFunctionArn custom resource function"
    Value: !GetAtt OrganizationsPolicyTypeFunction.Arn
