AWSTemplateFormatVersion: "2010-09-09"

Description: Roles required to deploy the AWS Organization

Parameters:
  environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development

Resources:
  ##
  # Organization deployment role
  ##
  OrganizationDeploymentRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /deployment/
      Policies:
        - PolicyName: deploy-organization
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowReadOrganization
                Effect: Allow
                Action:
                  - "organizations:Get*"
                  - "organizations:List*"
                  - "organizations:Describe*"
                Resource: "*"
              - Sid: AllowCrudOrganization1
                Effect: Allow
                Action:
                  - organizations:DeclineHandshake
                  - organizations:UntagResource
                  - organizations:DeleteOrganizationalUnit
                  - organizations:AcceptHandshake
                  - organizations:CancelHandshake
                  - iam:GetServiceLinkedRoleDeletionStatus
                  - organizations:RemoveAccountFromOrganization
                  - organizations:TagResource
                  - organizations:UpdateOrganizationalUnit
                  - iam:CreateServiceLinkedRole
                  - organizations:CloseAccount
                  - iam:DeleteServiceLinkedRole
                  - organizations:CreateOrganizationalUnit
                  - organizations:MoveAccount
                Resource:
                  - !Sub "arn:aws:organizations::${AWS::AccountId}:resourcepolicy/o-*/rp-*"
                  - !Sub "arn:aws:organizations:::policy/o-*/*/p-*"
                  - !Sub "arn:aws:organizations::${AWS::AccountId}:root/o-*/r-*"
                  - !Sub "arn:aws:organizations:::handshake/o-*/*/h-*"
                  - !Sub "arn:aws:organizations::${AWS::AccountId}:ou/o-*/ou-*"
                  - !Sub "arn:aws:organizations::${AWS::AccountId}:account/o-*/*"
                  - !Sub "arn:aws:iam:::role/*"
              - Sid: AllowCrudOrganization2
                Effect: Allow
                Action:
                  - organizations:LeaveOrganization
                  - organizations:EnableAllFeatures
                  - organizations:CreateAccount
                  - organizations:DeleteOrganization
                  - organizations:CreateOrganization
                Resource: "*" # Only * supported

  ##
  # Organization services deployment role
  ##
  OrganizationServicesDeploymentPermissionBoundaryPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "organizations:*"
              - "iam:*"
              - "sso-directory:*"
              - "sso:*"
              - "identitystore:*"
              - "s3:*"
              - "cloudwatch:*"
              - "logs:*"
              - "cloudtrail:*"
              - "lambda:*"
              - "cloudformation:*"
              - "sns:*"
            Resource: "*"

  OrganizationServicesDeploymentRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /deployment/
      # TODO restrict policies
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSOrganizationsFullAccess
        - arn:aws:iam::aws:policy/AWSCloudTrail_FullAccess
        - arn:aws:iam::aws:policy/AWSSSODirectoryAdministrator
        - arn:aws:iam::aws:policy/AWSSSOMasterAccountAdministrator
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccessV2
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      # TODO restrict permission boundary
      PermissionsBoundary: !Ref OrganizationServicesDeploymentPermissionBoundaryPolicy

Outputs:
  OrganizationDeploymentRoleArn:
    Description: ARN of the OrganizationDeploymentRole
    Value: !GetAtt OrganizationDeploymentRole.Arn
  OrganizationServicesDeploymentRoleArn:
    Description: ARN of the OrganizationServicesDeploymentRole
    Value: !GetAtt OrganizationServicesDeploymentRole.Arn
