AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Identity Center with permission sets

Parameters:
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development
  # https://dev.to/hayao_k/how-to-manage-aws-sso-account-assignments-in-cloudformaton-5bmm
  identityCenterInstanceArn:
    Type: String
    Description: ARN of an IAM Identity Center, e.g. 'arn:aws:sso:::instance/ssoins-xxxxxxxxxxxxxxxx'

Resources:
  AdministratorPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: Administrator
      Description: Administrator, allowed to do everything
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: environment
          Value: !Ref environment

  PowerUserPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: PowerUser
      Description: Power user based on AWS PowerUser policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/PowerUserAccess
      Tags:
        - Key: environment
          Value: !Ref environment

  ReadOnlyPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: ReadOnly
      Description: Read only access based on AWS ReadOnlyAccess policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Tags:
        - Key: environment
          Value: !Ref environment

Outputs:
  PermissionSets:
    Description: Identity center permission sets
    Value: !Sub
      - |
        {
          "Administrator": "${AdministratorPermissionSetArn}",
          "PowerUser": "${PowerUserPermissionSetArn}",
          "ReadOnly": "${ReadOnlyPermissionSetArn}"
        }
      - AdministratorPermissionSetArn: !GetAtt AdministratorPermissionSet.PermissionSetArn
        PowerUserPermissionSetArn: !GetAtt PowerUserPermissionSet.PermissionSetArn
        ReadOnlyPermissionSetArn: !GetAtt ReadOnlyPermissionSet.PermissionSetArn
