AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Identity Center with permission sets


Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development
  # https://dev.to/hayao_k/how-to-manage-aws-sso-account-assignments-in-cloudformaton-5bmm
  identityCenterInstanceArn:
    Type: String
    Description: ARN of an IAM Identity Center, e.g. 'arn:aws:sso:::instance/ssoins-xxxxxxxxxxxxxxxx'


Resources:
  # TODO Identity Center
  
  AdministratorPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: Administrator, allowed to do everything
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies: 
        - AdministratorAccess
      Name: Administrator
      Tags: 
        - Key: env
          Value: !Ref env
  PowerUserPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: Power user based on AWS PowerUser policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies: 
        - PowerUserAccess
      Name: PowerUser
      Tags: 
        - Key: env
          Value: !Ref env
  ReadOnlyPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: Read only access based on AWS ReadOnlyAccess policy
      InstanceArn: !Ref identityCenterInstanceArn
      ManagedPolicies: 
        - ReadOnlyAccess
      Name: ReadOnly
      Tags: 
        - Key: env
          Value: !Ref env


Outputs:
