AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Basic Organization with AWS Organizations


Parameters:
  env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development


Resources:
  Organization:
    DeletionPolicy: Retain
    Type: 'AWS::Organizations::Organization'
    Properties:
      FeatureSet: ALL
  DevelopmentOrganizationalUnit:
    Type: AWS::Organizations::OrganizationalUnit
    Properties: 
      Name: development
      ParentId: !GetAtt Organization.Id
      Tags: 
        - Key: environment
          Value: dev
  ProductionOrganizationalUnit:
    Type: AWS::Organizations::OrganizationalUnit
    Properties: 
      Name: production
      ParentId: !GetAtt Organization.Id
      Tags: 
        - Key: environment
          Value: prod


Outputs:
  ManagementAccountId:
    Description: Account ID of the organizations management account
    Value: !GetAtt Organization.ManagementAccountId
  ManagementAccountArn:
    Description: Account ARN of the organizations management account
    Value: !GettAtt Organization.ManagementAccountArn
  OrganizationId:
    Description: ID of the organization
    Value: !GettAtt Organization.Id
  OrganizationArn:
    Description: ID of the organization
    Value: !GettAtt Organization.Arn
