AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Organization service control policies
# Examples see https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples_general.html

Parameters:
  environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment e.g. dev for development
  organizationRootId:
    Type: String
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-organizationalunit.html#cfn-organizations-organizationalunit-parentid
    AllowedPattern: ^(r-[0-9a-z]{4,32})|(ou-[0-9a-z]{4,32}-[a-z0-9]{8,32})$
    Description: Root ID of the organization
  supportedRegions:
    Type: String
    Description: Comma separated list of supported regions

Resources:
  # https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps_examples_general.html#example-scp-deny-region
  EnableSupportedRegionsOnlyPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      Type: SERVICE_CONTROL_POLICY
      Name: !Sub "SCP-DenyNotSupportedRegions-${environment}"
      TargetIds:
        - !Ref organizationRootId
      Content:
        Version: 2012-10-17
        Statement:
          - Sid: !Sub "SCPDenyAllOutsideRequestedRegions"
            Effect: Deny
            NotAction:
              - "a4b:*"
              - "acm:*"
              - "aws-marketplace-management:*"
              - "aws-marketplace:*"
              - "aws-portal:*"
              - "budgets:*"
              - "ce:*"
              - "chime:*"
              - "cloudfront:*"
              - "config:*"
              - "cur:*"
              - "directconnect:*"
              - "ec2:DescribeRegions"
              - "ec2:DescribeTransitGateways"
              - "ec2:DescribeVpnGateways"
              - "fms:*"
              - "globalaccelerator:*"
              - "health:*"
              - "iam:*"
              - "importexport:*"
              - "kms:*"
              - "mobileanalytics:*"
              - "networkmanager:*"
              - "organizations:*"
              - "pricing:*"
              - "route53:*"
              - "route53domains:*"
              - "route53-recovery-cluster:*"
              - "route53-recovery-control-config:*"
              - "route53-recovery-readiness:*"
              - "s3:GetAccountPublic*"
              - "s3:ListAllMyBuckets"
              - "s3:ListMultiRegionAccessPoints"
              - "s3:PutAccountPublic*"
              - "shield:*"
              - "sts:*"
              - "support:*"
              - "trustedadvisor:*"
              - "waf-regional:*"
              - "waf:*"
              - "wafv2:*"
              - "wellarchitected:*"
            Resource: "*"
            Condition:
              # Enabled regions
              # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html
              StringNotEquals:
                aws:RequestedRegion: !Split [",", !Ref supportedRegions]
              # Superuser allowed to bypass region block
              # ArnNotLike:
              #   aws:PrincipalARN:
              #     - arn:aws:iam::*:role/OrganizationAdministrator
