AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Organization with AWS Organizations, Identity Center and SCPs

Parameters:
  environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development

Resources:
  OrganizationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        environment: !Ref environment
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: "./organization.yml"
      TimeoutInMinutes: 60

Outputs:
  ManagementAccountId:
    Description: Account ID of the organizations management account
    Value: !GetAtt
      - OrganizationStack
      - Outputs.ManagementAccountId
  OrganizationArn:
    Description: ID of the organization
    Value: !GetAtt
      - OrganizationStack
      - Outputs.OrganizationArn
