AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: Organization with AWS Organizations, Identity Center and SCPs

Parameters:
  environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development
  identityCenterInstanceArn:
    Type: String
    AllowedPattern: (^$|^arn:aws:sso:::instance/(sso)?ins-[a-zA-Z0-9-.]{16})
    Description: >
      ARN of an IAM Identity Center, e.g. 'arn:aws:sso:::instance/ssoins-xxxxxxxxxxxxxxxx'.
      Find by `aws sso-admin list-instances`.
    Default: ""
  organizationEmail:
    Type: String
    AllowedPattern: ^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$
    Description: >
      An email address like 'aws@your-domain.tld'.
      Each account will get a labeled address like 'aws+the-account-name@your-domain.tld'.
  supportedRegions:
    Type: String
    Description: >
      Comma separated list of supported regions. The first is the main region.
      See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html.
      Examples:
      - us-east-1 # US East (N. Virginia)
      - sa-east-1 # South America (São Paulo)
      - eu-central-1 # Europe (Frankfurt)
      - eu-central-2 # Europe (Zurich)
      - ap-southeast-1 # Asia Pacific (Singapore)
      These regions must be enabled in the account: https://us-east-1.console.aws.amazon.com/billing/home?region=eu-central-1#/account?AWS-Regions
    Default: "us-east-1,eu-central-1"

Conditions:
  HasIdentityCenterInstance: !Not [!Equals [!Ref identityCenterInstanceArn, ""]]

Resources:
  OrganizationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        environment: !Ref environment
        organizationEmail: !Ref organizationEmail
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: "./organization.yml"
      TimeoutInMinutes: 60

  CustomResourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        environment: !Ref environment
        organizationId: !GetAtt OrganizationStack.Outputs.OrganizationId
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: "./custom-resources.yml"
      TimeoutInMinutes: 60

  LoggingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        environment: !Ref environment
        managementAccountId: !GetAtt OrganizationStack.Outputs.ManagementAccountId
        organizationId: !GetAtt OrganizationStack.Outputs.OrganizationId
        organizationsAwsServiceAccessFunctionArn: !GetAtt CustomResourcesStack.Outputs.OrganizationsAwsServiceAccessFunctionArn
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: "./logging.yml"
      TimeoutInMinutes: 60

  IdentityStack:
    Type: AWS::CloudFormation::Stack
    Condition: HasIdentityCenterInstance
    Properties:
      Parameters:
        environment: !Ref environment
        identityCenterInstanceArn:
          !If [
            "HasIdentityCenterInstance",
            !Ref identityCenterInstanceArn,
            !Ref "AWS::NoValue",
          ]
        organizationRootId: !GetAtt OrganizationStack.Outputs.OrganizationRootId
        supportedRegions: !Ref supportedRegions
        organizationsAwsServiceAccessFunctionArn: !GetAtt CustomResourcesStack.Outputs.OrganizationsAwsServiceAccessFunctionArn
        cloudformationOrganizationsAccessFunctionArn: !GetAtt CustomResourcesStack.Outputs.CloudformationOrganizationsAccessFunctionArn
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: "./identity/identity.yml"
      TimeoutInMinutes: 60

  ServiceControlPoliciesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        environment: !Ref environment
        organizationRootId: !GetAtt OrganizationStack.Outputs.OrganizationRootId
        supportedRegions: !Ref supportedRegions
        organizationsPolicyTypeFunctionArn: !GetAtt CustomResourcesStack.Outputs.OrganizationsPolicyTypeFunctionArn
      Tags:
        - Key: environment
          Value: !Ref environment
      TemplateURL: "./service-control-policies.yml"
      TimeoutInMinutes: 60

Outputs:
  ManagementAccountId:
    Description: Account ID of the organizations management account
    Value: !GetAtt OrganizationStack.Outputs.ManagementAccountId
  OrganizationArn:
    Description: ID of the organization
    Value: !GetAtt OrganizationStack.Outputs.OrganizationArn
  PermissionSets:
    Description: Identity center permission sets
    Value:
      !If [
        HasIdentityCenterInstance,
        !GetAtt IdentityStack.Outputs.PermissionSets,
        "",
      ]
